<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\ConfigCommands' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\src\\Command\\ConfigCommands.php';
include_once $this->targetDirs[3].'\\src\\Service\\ConfigService.php';

$this->privates['App\Command\ConfigCommands'] = $instance = new \App\Command\ConfigCommands(NULL, ($this->privates['App\Repository\SourceRepository'] ?? $this->load('getSourceRepositoryService.php')), ($this->privates['App\Service\ConfigService'] ?? ($this->privates['App\Service\ConfigService'] = new \App\Service\ConfigService())));

$instance->setName('app:ChangeSource');

return $instance;
