<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\HomeController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\HomeController.php';
include_once $this->targetDirs[3].'\\src\\Service\\ConvertService.php';
include_once $this->targetDirs[3].'\\src\\Service\\ConfigService.php';

$this->services['App\Controller\HomeController'] = $instance = new \App\Controller\HomeController(new \App\Service\ConvertService(($this->privates['App\Repository\SourceRepository'] ?? $this->load('getSourceRepositoryService.php')), ($this->privates['App\Repository\CurrencyRepository'] ?? $this->load('getCurrencyRepositoryService.php')), ($this->privates['App\Service\ConfigService'] ?? ($this->privates['App\Service\ConfigService'] = new \App\Service\ConfigService()))));

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine' => ['services', 'doctrine', 'getDoctrineService.php', true],
    'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
    'router' => ['services', 'router', 'getRouterService', false],
    'session' => ['services', 'session', 'getSessionService.php', true],
]))->withContext('App\\Controller\\HomeController', $this));

return $instance;
