<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSEWJl9V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSEWJl9V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSEWJl9V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSEWJl9V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSEWJl9V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SEWJl9V',
    'container.build_id' => 'a8d74964',
    'container.build_time' => 1549468893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSEWJl9V');
